version: "3.8"

name: xupopter-runner
services:
  xupopter_runner:
    container_name: xupopter_runner
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "8089:8089"
    environment:
      - JWT_ACCESS_SECRET=1234
    networks:
      - feed-generator_feed-generator
networks:
  feed-generator_feed-generator:
    external: true